name: test diff


on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Web Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Upload coverage to Canyon
        uses: canyon-project/canyon-action@v1.0.19
